Added GitHub worklow actions for doxygen and basic CI (verifies the build, but runs no tests yet)
5G-MAG/rt-mbms-mw pull request #8
Opened 2021-10-06 09:36 UTC by kuehnhammer

2021-12-01 09:43 UTC, dsilhavy requested changes

2021-12-01 09:43 UTC, dsilhavy commented on .github/workflows/cmake_build.yml
> +        sudo apt install ssh g++ git libboost-atomic-dev libboost-thread-dev libboost-system-dev libboost-date-time-dev libboost-regex-dev libboost-filesystem-dev libboost-random-dev libboost-chrono-
Please add `sudo apt update` as first step otherwise this step fails

2021-12-01 09:43 UTC, dsilhavy commented on .github/workflows/doxygen.yml
> +    - uses: actions/checkout@v2
Please add name here `- name: Checkout`

2021-12-06 11:31 UTC, kuehnhammer commented
@dsilhavy -- I've added your files

2021-12-06 14:54 UTC, dsilhavy approved these changes

2021-12-06 14:54 UTC, merged